autogenerate:
  prompts:
    outfile: my_project/prompts.py

    prompts:
      - id: study-guide-outline
        major_version: 1

      - id: flashcard-generator
        major_version: 1

      - id: is-supported-by-notes-eval
        major_version: 1

      - id: is-professional-tone-eval
        major_version: 1
