name: Create .env file

inputs:
  openai-api-key:
    required: true
    type: string
  autoblocks-ingestion-key:
    required: true
    type: string

runs:
  using: composite

  steps:
    - name: Create .env file
      run: |
        touch .env
        echo "OPENAI_API_KEY=${{ inputs.openai-api-key }}" >> .env
        echo "AUTOBLOCKS_INGESTION_KEY=${{ inputs.autoblocks-ingestion-key }}" >> .env
