name: Autoblocks Testing

on:
  push: # Run on every push.
  schedule: # Run every day at ~7:17am PST.
    - cron: '17 15 * * *'
  workflow_dispatch: # Allow runs triggered from Autoblocks UI.
    inputs:
      autoblocks-overrides:
        type: string
        description: Overrides for Autoblocks-managed entities
        required: false

permissions:
  # Allow commenting on pull requests
  issues: write
  # Allow getting associated pull requests when event is type `push`
  pull-requests: write
  contents: read

jobs:
  py-autoblocks-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project:
          - Python/testing-sdk
          - Python/testing-sdk-with-prompt-sdk
          - Python/dspy
          - Python/pinecone

    defaults:
      run:
        shell: bash
        working-directory: ${{ matrix.project }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install poetry
        run: curl -sSL https://install.python-poetry.org | python3 -

      - name: Check pyproject.toml & poetry.lock are in sync
        run: poetry lock --check

      - name: Install dependencies
        run: poetry install

      - name: Run mypy
        run: poetry run mypy
        if: matrix.project == 'Python/testing-sdk'

      - name: Run Autoblocks tests
        run: npx autoblocks testing exec -- poetry run start
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          AUTOBLOCKS_API_KEY: ${{ secrets.AUTOBLOCKS_API_KEY }}
          AUTOBLOCKS_INGESTION_KEY: ${{ secrets.AUTOBLOCKS_INGESTION_KEY }}
          PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}

  js-autoblocks-tests:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: JavaScript/testing-sdk

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Run Autoblocks tests
        run: npx autoblocks testing exec -- npm run start
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          AUTOBLOCKS_API_KEY: ${{ secrets.AUTOBLOCKS_API_KEY }}
